# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52878bf2a887f932caac0cffd9b25619b4b3614a1020a757c9295278c941e667471164c663cb6e17a9e312561636b4ba0638a0b45775f8f13044c2c3b9689bf0

test:
  secret_key_base: c9a87414689342c43d323575ce2fcb1c65ce671d06328fe96533c1f9ee99e54bbc9b7de6337d46a62b2d2cbcec61dd505dc8a14ff3b2f9444b25638966ec8b80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
